import { IsString, IsNotEmpty, IsOptional } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class TrackPageViewDto {
  @ApiProperty({ description: 'URL path visited', example: '/questions' })
  @IsString()
  @IsNotEmpty()
  path: string;

  @ApiPropertyOptional({ description: 'Unique visitor ID generated by client', example: 'visitor_123456' })
  @IsString()
  @IsOptional()
  visitorId?: string;
}
